// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Minhaapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinhaApi.Models.LoteMinerio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoLote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_lote");

                    b.Property<DateTime>("DataProducao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_producao");

                    b.Property<string>("LocalizacaoAtual")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("localizacao_atual");

                    b.Property<string>("MinaOrigem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("mina_origem");

                    b.Property<decimal?>("P")
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("p");

                    b.Property<decimal?>("SiO2")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("si_o2");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TeorFe")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("teor_fe");

                    b.Property<decimal>("Toneladas")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("toneladas");

                    b.Property<decimal>("Umidade")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("umidade");

                    b.HasKey("Id")
                        .HasName("pk_lotes_minerio");

                    b.HasIndex("CodigoLote")
                        .IsUnique()
                        .HasDatabaseName("ix_lotes_minerio_codigo_lote");

                    b.ToTable("lotes_minerio", "public");
                });

            modelBuilder.Entity("MinhaApi.Models.MovimentacaoLote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_movimentacao");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("local");

                    b.Property<int>("LoteMinerioId")
                        .HasColumnType("integer")
                        .HasColumnName("lote_minerio_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_movimentacoes_lote");

                    b.HasIndex("LoteMinerioId")
                        .HasDatabaseName("ix_movimentacoes_lote_lote_minerio_id");

                    b.ToTable("movimentacoes_lote", "public");
                });

            modelBuilder.Entity("MinhaApi.Models.MovimentacaoLote", b =>
                {
                    b.HasOne("MinhaApi.Models.LoteMinerio", "LoteMinerio")
                        .WithMany()
                        .HasForeignKey("LoteMinerioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_lote_lotes_minerio_lote_minerio_id");

                    b.Navigation("LoteMinerio");
                });
#pragma warning restore 612, 618
        }
    }
}
